#!/bin/sh
#################################
# checkfixwifi - Check whether WiFi wlan0 interface is currently associated with a
#                192.168.x.x network. If not, disable that interface, wait a bit,
#                and then re-enable it.  Lather, rinse, repeat...
#
# HISTORICAL INFORMATION -
#
#  2020-10-07  msipin  Created.
#################################

IFACE=wlan0
SUBNET="192.168."


echo "`date` - Starting $0..."

# Sleep a while, to let the system come up completely
sleep 120

while [ 1 ]
do

    cnt=`ifconfig ${IFACE} | grep inet.addr | grep -c ${SUBNET}`

    if [ ""$cnt"" -ne 1 ]
    then
	echo "`date` - $IFACE is not currently associated with a ${SUBNET}.. subnet!"

	# Bring interface down
	ifdown ${IFACE} >/dev/null 2>&1

	# Wait a bit to let interface settle
	sleep 10

	# Bring interface back up
	ifup ${IFACE} >/dev/null 2>&1

	# Sleep a bit to give interface the chance to reassociate
	sleep 40
    else
	#echo "`date` - ${IFACE} *is* currently associated with a ${SUBNET} subnet."

	# Sleep until time to check again
	sleep 60
    fi

done

exit 0

