#!/bin/sh
#################################
# checkfixwifi - Check whether WiFi wlan0 interface is currently associated with a
#                192.168.x.x network. If not, disable that interface, wait a bit,
#                and then re-enable it.  Lather, rinse, repeat...
#
# HISTORICAL INFORMATION -
#
#  2020-10-07  msipin  Created.
#################################

#IFACE="wlan0"
IFACE="eth0"
SUBNET="192.168."


echo "`date` - Starting $0..."

# Sleep a while, to let the system come up completely
sleep 120

while [ 1 ]
do
    cnt=`ifconfig ${IFACE} | grep inet.addr | grep -c ${SUBNET}`

    if [ ""$cnt"" -ne 1 ]
    then
	echo "`date` - $IFACE is not currently associated with a ${SUBNET}.. subnet!"

	# Bring interface down
	ifdown --force ${IFACE} >/dev/null 2>&1

	# Wait a bit to let interface settle
	sleep 10

	# Bring interface back up
	ifup --force ${IFACE} >/dev/null 2>&1

    fi

    # Sleep a while to let any changes propagate
    sleep 40

done

exit 0

