#!/bin/bash
# Script: pitemp
# Purpose: Display the ARM CPU and GPU  temperature of Raspberry Pi 2/3
# Author: Vivek Gite <www.cyberciti.biz> under GPL v2.x+
# -------------------------------------------------------

LOG_FORMAT="N"

if [ $# -ge 1 ]
then
        if [ ""$1"" = "-l" ]
        then
                LOG_FORMAT="Y"
        else
                echo
                echo "Error: Invalid argument to $0 - [$1]"
                echo
                exit 2
        fi
fi

# Get CPU and GPU temperatures
cpu_C=`cat /sys/class/thermal/thermal_zone0/temp | awk '{ printf "%3.1f", $1/1000; }'`
cpu_F=`echo ${cpu_C} | awk '{ printf "%4.1f", ($1 *9.0/5.0 + 32.0); }'`
gpu_C=`sudo /opt/vc/bin/vcgencmd measure_temp | awk -F"=" '{ print $2 }' | awk -F"'" '{ print $1 }'`
gpu_F=`echo ${gpu_C} | awk '{ printf "%4.1f", ($1 *9.0/5.0 + 32.0); }'`


if [ $LOG_FORMAT = "Y" ]
then
        echo "$(date --rfc-3339=seconds),$(hostname),${gpu_C},C,${gpu_F},F,${cpu_C},C,${cpu_F},F"
else
        echo
        echo "$(date) @ $(hostname)"
        echo "-------------------------------------------"
        echo "GPU temp: ${gpu_C} C    ${gpu_F} F"
        echo "CPU temp: ${cpu_C} C    ${cpu_F} F"
        echo
fi

exit 0

